Repository googleapis/genai-toolbox, pull requests merged in 2025-09, with the labels that each got.

#1352 feat(prebuiltconfig/neo4j): Add prebuiltconfig support for neo4j
  .github/release-please.yml
  cmd/root_test.go
  docs/en/how-to/connect-ide/neo4j_mcp.md
  docs/en/reference/prebuilt-tools.md
  internal/prebuiltconfigs/prebuiltconfigs_test.go
  internal/prebuiltconfigs/tools/neo4j.yaml
Labels: docs: deploy-preview

#1223 feat(tools/bigquery-analyze-contribution): Add analyze contribution tool
  cmd/root.go
  cmd/root_test.go
  docs/en/resources/tools/bigquery/bigquery-analyze-contribution.md
  internal/prebuiltconfigs/tools/bigquery.yaml
  internal/tools/bigquery/bigqueryanalyzecontribution/bigqueryanalyzecontribution.go
  internal/tools/bigquery/bigqueryanalyzecontribution/bigqueryanalyzecontribution_test.go
  tests/bigquery/bigquery_integration_test.go
Labels: docs: deploy-preview, release candidate

#1408 feat(source/cloudsqladmin): Add cloud sql admin source
  cmd/root.go
  docs/en/resources/sources/cloud-sql-admin.md
  internal/sources/cloudsqladmin/cloud_sql_admin.go
  internal/sources/cloudsqladmin/cloud_sql_admin_test.go
Labels: release candidate

#1448 feat(source/alloydb-admin): Add user agent and attach alloydb api in alloydb-admin source
  docs/en/resources/tools/alloydb/alloydb-list-instances.md
  docs/en/resources/tools/alloydb/alloydb-list-users.md
  internal/sources/alloydbadmin/alloydbadmin.go
  internal/tools/alloydb/alloydbgetcluster/alloydbgetcluster.go
  internal/tools/alloydb/alloydblistclusters/alloydblistclusters.go
  internal/tools/alloydb/alloydblistinstances/alloydblistinstances.go
  internal/tools/alloydb/alloydblistusers/alloydblistusers.go
Labels: release candidate

#1436 feat(tools/alloydb-get-user): Add get-user tool for alloydb
  cmd/root.go
  cmd/root_test.go
  docs/en/resources/tools/alloydb/alloydb-get-user.md
  internal/prebuiltconfigs/tools/alloydb-postgres-admin.yaml
  internal/tools/alloydb/alloydbgetuser/alloydbgetuser.go
  internal/tools/alloydb/alloydbgetuser/alloydbgetuser_test.go
  tests/alloydb/alloydb_integration_test.go
Labels: release candidate

#1403 feat(prebuilt/cloudsqlpg): add cloud sql pg create instance tool
  cmd/root.go
  docs/en/resources/tools/cloudsql/cloudsqlpgcreateinstances.md
  internal/tools/cloudsqlpg/cloudsqlpgcreateinstances/cloudsqlpgcreateinstances.go
  internal/tools/cloudsqlpg/cloudsqlpgcreateinstances/cloudsqlpgcreateinstances_test.go
  tests/cloudsqlpg/cloud_sql_pg_create_instances_test.go
Labels: release candidate

#1453 feat(prebuilt/cloudsql): add cloud sql create database tool.
  cmd/root.go
  docs/en/resources/tools/cloudsql/cloudsqlcreatedatabase.md
  internal/tools/cloudsql/cloudsqlcreatedatabase/cloudsqlcreatedatabase.go
  internal/tools/cloudsql/cloudsqlcreatedatabase/cloudsqlcreatedatabase_test.go
  tests/cloudsql/cloud_sql_create_database_test.go
Labels: release candidate

#1454 feat(prebuilt/cloudsql): Add list databases tool for cloud sql
  cmd/root.go
  docs/en/resources/tools/cloudsql/cloudsqllistdatabases.md
  internal/tools/cloudsql/cloudsqllistdatabases/cloudsqllistdatabases.go
  internal/tools/cloudsql/cloudsqllistdatabases/cloudsqllistdatabases_test.go
  tests/cloudsql/cloud_sql_list_databases_test.go
Labels: release candidate

#1455 feat(prebuilt/cloudsql): Package cloud sql tools
  cmd/root_test.go
  internal/prebuiltconfigs/prebuiltconfigs_test.go
  internal/prebuiltconfigs/tools/cloud-sql-mssql-admin.yaml
  internal/prebuiltconfigs/tools/cloud-sql-mysql-admin.yaml
  internal/prebuiltconfigs/tools/cloud-sql-postgres-admin.yaml
Labels: release candidate

#1468 fix(tools/alloydb): Update parameter names and set default description for alloydb control plane tools
  docs/en/resources/tools/alloydb/alloydb-get-cluster.md
  docs/en/resources/tools/alloydb/alloydb-get-instance.md
  docs/en/resources/tools/alloydb/alloydb-get-user.md
  docs/en/resources/tools/alloydb/alloydb-list-clusters.md
  docs/en/resources/tools/alloydb/alloydb-list-instances.md
  docs/en/resources/tools/alloydb/alloydb-list-users.md
  internal/tools/alloydb/alloydbgetcluster/alloydbgetcluster.go
  internal/tools/alloydb/alloydbgetinstance/alloydbgetinstance.go
  internal/tools/alloydb/alloydbgetuser/alloydbgetuser.go
  internal/tools/alloydb/alloydblistclusters/alloydblistclusters.go
  internal/tools/alloydb/alloydblistinstances/alloydblistinstances.go
  internal/tools/alloydb/alloydblistusers/alloydblistusers.go
  tests/alloydb/alloydb_integration_test.go
Labels: release candidate

#1331 feat(tools/alloydb-create-cluster): Add custom tool kind for AlloyDB create cluster
  cmd/root.go
  docs/en/resources/tools/alloydb/alloydb-create-cluster.md
  internal/prebuiltconfigs/tools/alloydb-postgres-admin.yaml
  internal/tools/alloydb/alloydbcreatecluster/alloydbcreatecluster.go
  internal/tools/alloydb/alloydbcreatecluster/alloydbcreatecluster_test.go
  tests/alloydb/alloydb_integration_test.go
Labels: release candidate

#1437 docs(observability): Add documentation and tests for observability tools
  docs/en/reference/prebuilt-tools.md
  docs/en/resources/tools/cloudmonitoring/_index.md
  docs/en/resources/tools/cloudmonitoring/cloud-monitoring-query-prometheus.md
  internal/prebuiltconfigs/tools/alloydb-postgres-observability.yaml
Labels: docs: deploy-preview, release candidate

#1474 feat(prebuilt/mysql): Add a new tool to show query plan of a given query in MySQL
  cmd/root_test.go
  docs/en/reference/prebuilt-tools.md
  internal/prebuiltconfigs/tools/cloud-sql-mysql.yaml
  internal/prebuiltconfigs/tools/mysql.yaml
Labels: release candidate

#1471 feat(tools/mysql-list-active-queries): Add a new tool to list ongoing queries in a MySQL instance
  cmd/root.go
  cmd/root_test.go
  docs/en/resources/sources/cloud-sql-mysql.md
  docs/en/resources/sources/mysql.md
  docs/en/resources/tools/mysql/mysql-list-active-queries.md
  internal/prebuiltconfigs/tools/cloud-sql-mysql.yaml
  internal/prebuiltconfigs/tools/mysql.yaml
  internal/tools/mysql/mysqllistactivequeries/mysqllistactivequeries.go
  internal/tools/mysql/mysqllistactivequeries/mysqllistactivequeries_test.go
  tests/mysql/mysql_integration_test.go
Labels: release candidate

#1382 feat(tools/bigquery-search-catalog): Add support for bigquery-search-catalog tool
  cmd/root.go
  cmd/root_test.go
  docs/en/reference/prebuilt-tools.md
  docs/en/resources/sources/bigquery.md
  docs/en/resources/tools/bigquery/bigquery-search-catalog.md
  internal/prebuiltconfigs/tools/bigquery.yaml
  internal/sources/bigquery/bigquery.go
  internal/tools/bigquery/bigquerysearchcatalog/bigquerysearchcatalog.go
  internal/tools/bigquery/bigquerysearchcatalog/bigquerysearchcatalog_test.go
  tests/bigquery/bigquery_integration_test.go
Labels: release candidate

#1479 feat(tools/mysql-list-table-fragmentation): Add a new tool to list table fragmentation in a MySQL instance
  cmd/root.go
  cmd/root_test.go
  docs/en/resources/sources/cloud-sql-mysql.md
  docs/en/resources/sources/mysql.md
  docs/en/resources/tools/mysql/mysql-list-table-fragmentation.md
  internal/prebuiltconfigs/tools/cloud-sql-mysql.yaml
  internal/prebuiltconfigs/tools/mysql.yaml
  internal/tools/mysql/mysqllisttablefragmentation/mysqllisttablefragmentation.go
  internal/tools/mysql/mysqllisttablefragmentation/mysqllisttablefragmentation_test.go
  tests/common.go
  tests/mysql/mysql_integration_test.go
  tests/tool.go
Labels: release candidate

#1518 style: run linter
  internal/sources/alloydbadmin/alloydbadmin_test.go
  internal/sources/bigquery/bigquery.go
  internal/sources/cloudmonitoring/cloud_monitoring.go
  internal/tools/alloydb/alloydbcreatecluster/alloydbcreatecluster.go
  internal/tools/alloydb/alloydbcreatecluster/alloydbcreatecluster_test.go
  internal/tools/alloydb/alloydbcreateinstance/alloydbcreateinstance.go
  internal/tools/alloydb/alloydbcreateinstance/alloydbcreateinstance_test.go
  internal/tools/alloydb/alloydbcreateuser/alloydbcreateuser.go
  internal/tools/alloydb/alloydbcreateuser/alloydbcreateuser_test.go
  internal/tools/alloydb/alloydbgetcluster/alloydbgetcluster.go
  internal/tools/alloydb/alloydbgetcluster/alloydbgetcluster_test.go
  internal/tools/alloydb/alloydbgetinstance/alloydbgetinstance.go
  internal/tools/alloydb/alloydbgetinstance/alloydbgetinstance_test.go
  internal/tools/alloydb/alloydbgetuser/alloydbgetuser.go
  internal/tools/alloydb/alloydbgetuser/alloydbgetuser_test.go
  internal/tools/alloydb/alloydblistclusters/alloydblistclusters.go
  internal/tools/alloydb/alloydblistclusters/alloydblistclusters_test.go
  internal/tools/alloydb/alloydblistinstances/alloydblistinstances.go
  internal/tools/alloydb/alloydblistinstances/alloydblistinstances_test.go
  internal/tools/alloydb/alloydblistusers/alloydblistusers.go
  internal/tools/alloydb/alloydblistusers/alloydblistusers_test.go
  internal/tools/alloydb/alloydbwaitforoperation/alloydbwaitforoperation.go
  internal/tools/bigquery/bigqueryanalyzecontribution/bigqueryanalyzecontribution.go
  internal/tools/bigquery/bigquerysearchcatalog/bigquerysearchcatalog.go
  internal/tools/bigquery/bigquerysearchcatalog/bigquerysearchcatalog_test.go
  internal/tools/cloudmonitoring/cloudmonitoring.go
  internal/tools/mssql/mssqllisttables/mssqllisttables.go
  internal/tools/mssql/mssqllisttables/mssqllisttables_test.go
  internal/tools/mysql/mysqllisttables/mysqllisttables.go
  internal/tools/mysql/mysqllisttables/mysqllisttables_test.go
  internal/tools/postgres/postgreslisttables/postgreslisttables.go
  internal/tools/spanner/spannerlisttables/spannerlisttables.go
  internal/tools/sqlite/sqliteexecutesql/sqliteexecutesql_test.go
  internal/tools/sqlite/sqlitesql/sqlitesql_test.go
  tests/alloydb/alloydb_integration_test.go
  tests/alloydb/alloydb_wait_for_operation_test.go
  tests/alloydbpg/alloydb_pg_integration_test.go
  tests/cloudmonitoring/cloud_monitoring_integration_test.go
  tests/common.go
  tests/mssql/mssql_integration_test.go
  tests/mysql/mysql_integration_test.go
  tests/spanner/spanner_integration_test.go
  tests/sqlite/sqlite_integration_test.go
Labels: release candidate

#1570 fix(tool/mongodb-find): fix find tool `limit` field
  internal/tools/mongodb/mongodbfind/mongodbfind.go
  tests/mongodb/mongodb_integration_test.go
Labels: release candidate
